version: '3.7'

services:
  # development environment for wifis-connect
  wifis-connect:
    init: true
    build:
      dockerfile: Dockerfile
      context: .
    image: wifis-connect:dev
    container_name: wifis-connect
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - .:/app